### PR TITLE
#34: Fix duplicate boat issue

### LINKED ISSUE #34: Fix duplicate boat issue
There is a duplicate data issue, it doesn't affect the app's use it is just a visualized bug:

Screenshot 2023-07-26 at 10 51 18 AM

We can simply `unique` the data set to resolve this

### PR DESCRIPTION
**Pull request by murtza**
Closes #34

### CODE REVIEW

**Review by schrockwell — APPROVED** [review]
Good as a stop-gap, but we will want to make this configurable via #32

**Comment by bcardarella** [comment]
@schrockwell I actually don't want to do this as I think this will result in the wrong data being shown at times. There are duplicate position devices and some of the devices are less than ideal positional resolution. For example, on Echo the boat has an AIS system that only reports once every few minutes and that is the duplicate. This implementation doesn't ensure that lower resolution will be selected. I am OK keeping the duplicate boat for now and waiting for @CaptChrisD to implement a priority ordering and probably also device selection function when we look towards V2 in October.

**Review by schrockwell — CHANGES_REQUESTED** [review]
My mistake - unapproving per Brian

**Comment by schrockwell** [comment]
@bcardarella Roger that. On #46 I could add a per-boat setting to let us select the primary position data source on the web end. So we'll still have all the data but just filter what is displayed. Would be a simple solution for now.

**Comment by bcardarella** [comment]
@schrockwell that may be a good middle ground for now

**Comment by bcardarella** [comment]
Closed with #46

**Pull request closed without merging**
